- name: restart apache2
  service:
    name: "{{ debian_apache }}"
    state: restarted
  when: "ansible_os_family == 'Debian'"
  ignore_errors: yes
- name: restart httpd
  service:
    name: "{{ redhat_apache }}"
    state: restarted
  when: "ansible_os_family == 'RedHat'"
  ignore_errors: yes
