--- #Apt_Repo Module / Apt_Key
- hosts: appserver
  user: teste
  become: yes
  gather_facts: no
  tasks:
  - name: Install a dependency pkg
    apt:
      pkg: python-apt
      state: latest
  
  - name: Adding Repo Key
    apt_key:
      url: 'https://dl-ssl.google.com/linux/linux_signing_key.pub'
      state: present

  - name: Add Google Repo
    apt_repository:
      repo: 'deb http://dl.google.com/linux/deb/ stable main non-free'
      state: present