--- # At Module Example
- hosts: apacheweb
  user: test
  become: yes
  gather_facts: no
  tasks:
  - name: AT Module
    at:
      command: "ls -al /var/log > /home/teste/at.log"
      count: 1
      units: minutes
