--- #Cron Example
- hosts: apacheweb
  user: teste
  connection: ssh
  gather_facts: no
  tasks:
  - name: Add a cron job Teste User
    cron:
      name: "List Files"
      minute: "0"
      hour: "1"
      job: "ls -al > /home/teste/"
