--- #Fetch Module Example
- hosts: appserver
  user: teste
  become: yes
  tasks:
  - name: Copy remote hosts file to control server
    fetch:
      src: /etc/hosts
      dest: /tmp/hosts
  - name: Copy remote files with flat parameter
    fetch:
      src: /etc/hosts
      dest: /tmp/{{ ansible_hostname }}
      flat: yes
      
