--- #Group Module
- hosts: apacheweb
  user: teste
  become: yes
  gather_facts: no
  tasks:
  - name: Adicionando usuarios
    user:
      name: john
      state: present
      shell: /bin/bash
      uid: "24500" 
  - name: Adicionando novo grupo
    group:
      name: groupnovo
      state: present
      gid: 2500
      
