--- #HTPasswd module
- hosts: control
  user: teste
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Adicionando usuario para autenticacao web
    htpasswd: 
      path: /etc/apache2/.htpasswd