--- #SELinux Example
- hosts: apacheweb
  user: teste
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Change SELinux Configuration to Permissive
    selinux:
      policy: targeted
      state: permissive
