--- #Wait for Module
- hosts: apacheweb
  user: teste
  become: yes
  gather_facts: no
  tasks:
  - name: Install Tomcat
    apt:
      pkg: tomcat8
      state: installed
  - name: Waiting for port  8080 to listen
    wait_for:
      port: 8080
      state: started
  - name: Verify lynx installation
    apt:
      pkg: lynx
      state: present

