--- #Test Jinja2
- hosts: apacheweb
  user: teste
  become: yes
  gather_facts: yes
  vars:
    userName: teste
    userPassword: senha123
    connectionType: ssh
  tasks:
  - name: Instala de acordo com o sistema
    template:
      src: /home/bruno/Documentos/workspace/infra/ansible/roles/webserver/files/teste.conf
      dest: /tmp/teste.conf.j2
      owner: teste
      group: teste
      mode: 750
    delegate_to: 127.0.0.1