--- #Start App Playbook example
- hosts: apacheweb
  user: teste
  become: yes
  connection: ssh 
  gather_facts: no
  tasks:
  - name: Install telnet
    apt:
      pkg: telnet
      state: latest
  - name: Install lynx
    apt:
      pkg: lynx
      state: latest
  - name: List Home
    command: ls -al /home/teste


    # ansible-playbook startat.yml --start-at-task='List Home' --private-key ~/.ssh/ansible // Start em um ponto especific