--- #WebPlaybook
- hosts: apacheweb
  user: testes
  become: yes
  connection: ssh
  gather_facts: no
  vars_files:
  - variables/variables.yml
  tasks:
  - include: packages/packages.yml
  - include: commands/commands.yml
  handlers:
  - include: handler/handler.yml