- name: Install Apache2 (Debian)
  apt:
    pkg: "{{ debian_apache }}"
    state: latest
  when: "ansible_os_family == 'Debian'"
  notify: restart apache2 

- name: Install Httpd (Centos/RedHat)
  yum:
    pkg: "{{ redhat_apache }}"
    state: latest
  when: "ansible_os_family == 'RedHat'"
  notify: restart httpd