--- #Conditional Playbooks and when example 
- hosts: all
  user: teste
  become: yes
  vars:
    playbook_type: conditional_example
  vars_files:
    - conf/copyright.yml
    - conf/webdefaults.yml 
  tasks: 
    - name: Install Apache Web Server
      command: yum remove -y httpd
      when: ansible_os_family == "RedHat"
    - name: Install Apache to the distribution type
      command: apt purge -y apache2
      when: ansible_os_family == "Debian"
      