--- #Loops playbook 
- hosts: apacheweb
  user: teste
  become: yes
  gather_facts: no
  tasks:
    - name: Add users
      user: name={{ item }} state=present
      with_items:
        - bruno
        - paola
        - gordinha