--- #First playbook study
- hosts: apacheweb
  become: yes
  gather_facts: yes
  vars:
    playbook_version: 0.1b
  vars_files:
  - conf/copyright.yml
  - conf/webdefaults.yml
  vars_prompt:
    - name: web_domain
      prompt: web_domain

