--- #Tags Example
- hosts: control
  user: teste
  become: yes
  gather_facts: no
  tasks:
  - name: Installing packages
    yum:
      pkg: "{{ item }}"
      state: latest
    with_items:
    - telnet
    - lynx
    tags: packages
  - name: Verifing if the telnet is currently installed
    raw: yum list installed | grep telnet
    register: telnetResult 
  - debug:
      msg: The package "{{ telnetResult }}"