--- #Until Example 
- hosts: control
  user: teste
  become: yes
  gather_facts: no
  tasks:
  - name: Installing Apache
    yum:
      pkg: httpd
      state: latest
  - name: Verify Apache installation
    command: systemctl status httpd
    register: httpd_status
    until: httpd_status.stdout.find("active (running)") != -1
    retries: 5
    delay: 5
  - debug:
      msg: httpd_status


