---
- hosts: appserver
  user: teste
  become: yes
  gather_facts: no 
  tasks:
  - name: Adicionando usuarios
    user:
      name: "{{ item }}"
      state: present
    with_items:
      - gordinha
      - bruce
      - matilda
    