--- 
- hosts: appserver
  user: teste
  become: yes
  gather_facts: no 
  tasks:
  - name: Instala Apache
    apt:
      pkg: apache2
      state: present
    notify: Apache2_Restart
  
  handlers:
  - name: Apache2_Restart
    service:
      name: apache2 
      state: restarted