---
- hosts: all
  user: teste
  become: yes
  gather_facts: no 
  tasks: 
  - name: Uptime
    command: uptime > uptime.log
  - name: Lista /var
    command: ls /var > /home/teste/var.log
    run_once: true